//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Movie_ReviewDBEntities : DbContext
    {
        public Movie_ReviewDBEntities()
            : base("name=Movie_ReviewDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cast_tbl> Cast_tbl { get; set; }
        public virtual DbSet<Movies_tbl> Movies_tbl { get; set; }
        public virtual DbSet<News_tbl> News_tbl { get; set; }
        public virtual DbSet<Rating_tbl> Rating_tbl { get; set; }
        public virtual DbSet<Reviews_tbl> Reviews_tbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tasks_tbl> Tasks_tbl { get; set; }
        public virtual DbSet<Users_tbl> Users_tbl { get; set; }
    }
}
