//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev3
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_tbl
    {
        public int NewsID { get; set; }
        public string NewsHeader { get; set; }
        public string NewsFirstParagraph { get; set; }
        public string AllOfTheNews { get; set; }
        public Nullable<int> MovieID { get; set; }
        public System.DateTime NewsDate { get; set; }
        public string NewsHeader_tr { get; set; }
        public string NewsFirstParagraph_tr { get; set; }
    
        public virtual Movies_tbl Movies_tbl { get; set; }
    }
}
