//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cast
    {
        public string CastName { get; set; }
        public string CastRole { get; set; }
        public Nullable<int> MovieID { get; set; }
        public int CastID { get; set; }
    
        public virtual Movie_tbl Movie_tbl { get; set; }
    }
}
