//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments_tbl
    {
        public string Comments { get; set; }
        public string UserName { get; set; }
        public int MovieID { get; set; }
        public int CommentID { get; set; }
    
        public virtual Movie_tbl Movie_tbl { get; set; }
        public virtual Users_Tbl Users_Tbl { get; set; }
    }
}
