//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Movie_HunterEntities3 : DbContext
    {
        public Movie_HunterEntities3()
            : base("name=Movie_HunterEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cast> Casts { get; set; }
        public virtual DbSet<Comments_tbl> Comments_tbl { get; set; }
        public virtual DbSet<Movie_tbl> Movie_tbl { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Rating_tbl> Rating_tbl { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Users_Tbl> Users_Tbl { get; set; }
    }
}
