//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating_tbl
    {
        public int RatingID { get; set; }
        public double Rating { get; set; }
        public string MovieID { get; set; }
        public string UserName { get; set; }
    }
}
