//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews_tbl
    {
        public int ReviewID { get; set; }
        public int MovieId { get; set; }
        public string UserName { get; set; }
        public string ReviewTitle { get; set; }
        public int RatingID { get; set; }
        public string Review { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
    
        public virtual Movies_tbl Movies_tbl { get; set; }
        public virtual Rating_tbl Rating_tbl { get; set; }
        public virtual Users_tbl Users_tbl { get; set; }
    }
}
