//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks_tbl
    {
        public int TaskID { get; set; }
        public string Task_Avatar { get; set; }
        public int Task_Date_Day { get; set; }
        public string Task_Date_Month { get; set; }
        public string Task_Header { get; set; }
        public string Full_Task { get; set; }
    }
}
